### ISSUE TITLE
Fedora 27 introduces some issues

### ISSUE THREAD

**Issue by mikew02** [nsmoooose/csp#3]
scons 3.0.1 seems to expect Python3 syntax in the Sconstruct file. 
If I use an earlier version of scons, everything appears to build successfully but sim.py complains about at least one missing python file that should have been automatically generated.

**Comment by nsmoooose** [comment]
I also noticed this during Christmas when I upgraded my Linux machine.

scons in Fedora 27 is running with Python 3 and all the build tool extensions written for CSP 
to compile is in Python 2.

I guess it is finally time to take the big leap and convert all the python scripts to python 3. This will
take some time for me to solve.

I already have a branch that builds the entire project (not able to run the simulator though).

I will keep you posted on the progress.

/Henrik N

**Comment by nsmoooose** [comment]
It actually compiles completely with latest scons if you execute the build like this:
`python2 /usr/bin/scons -j20 all`

But I still cannot run it. So more troubleshooting is needed.

**Comment by mikew02** [comment]
Thanks for the python2 command. It's nice to avoid python3 whenever possible as I don't use it for anything else.

Presumably you're seeing this now when trying to run:
No module named _cspsim_module
Unable to import cspsim.py from csp/cspsim/.bin.

**Comment by nsmoooose** [comment]
Yes I got to the same point.

After some poking around I realized that we have upgraded the OS and gotten a new OpenSceneGraph version. And the old one has been removed.

This in turns means that we need to recompile csp-osgal since it depends on the uninstalled version of OpenSceneGraph. That is why the python module cannot be loaded.

This section from README.rst is needed:

```
cd csp-osgal
# WARNING remove all files not in version control from this project.
git clean -xf
ccmake .
make
sudo make install
```

**Comment by nsmoooose** [comment]
The move to python 3 must be done sooner than later. 

https://pythonclock.org/

**Comment by nsmoooose** [comment]
Let me know if this fixed your issue.

/Henrik N

**Comment by mikew02** [comment]
Everything working splendidly now. Thank you again!

**Comment by mikew02** [comment]
Still OK with Fedora 29 so will close this one

**Comment by nsmoooose** [comment]
Nice to hear.
/henrik
